In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("C:/Jasbir/Learning/100 days of ML learning/100-Days-Of-ML-Code-master/datasets/Data.csv")

In [7]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [8]:
y = df['Purchased']
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [9]:
x = df.iloc[:,:-1].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
y= df.iloc[:,-1:].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [7]:
#X = df.iloc[ :,:-1] # iloc[start_row:end_row,:column] if we don't used , it will give you same results.
#loc[] vs iloc[] is loc gets DataFrame rows & columns by labels/names and iloc[] gets by integer Index/position.
#X = df.loc[1:5,:'Salary'] # it take by name 
#print(X)

In [8]:
arr1 = np.array([[[2,17], [45, 78],[7,8],[98,99]], [[88, 92], [60, 76],[89,90],[101,102]],[[76,33],[20,18],[67,56],[30,40]]])

In [9]:
arr1

array([[[  2,  17],
        [ 45,  78],
        [  7,   8],
        [ 98,  99]],

       [[ 88,  92],
        [ 60,  76],
        [ 89,  90],
        [101, 102]],

       [[ 76,  33],
        [ 20,  18],
        [ 67,  56],
        [ 30,  40]]])

In [10]:
arr1[2:,3]

array([[30, 40]])

In [11]:
# #from sklearn.preprocessing import Imputer
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
# imputer = imputer.fit(x.iloc[ : , 1:3])
# x.iloc[ : , 1:3] = imputer.transform(x.iloc[ : , 1:3])

# Handling missing value

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
imputer = imputer.fit(x[ : , 1:3]) 
#iloc and loc both works with dataframe not with array so imputer.fit(x.iloc[ :,1:3]) not work
x[ : , 1:3] = imputer.transform(x[ : , 1:3])

In [12]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical data 

In [13]:
# Label encoding
from sklearn.preprocessing import LabelEncoder
#creating an instance of label encoder
labelEncoder = LabelEncoder()
#assigning numerical value and storing it into another column or same column
x[:,0] = labelEncoder.fit_transform(x[:,0])
x[:,0]
# In Label encoding we replace the categorical value with a numeric value between 0 and the number of classes minus 1
# the numbering is assigned in alphabetical order
# Drawback of Label encoding:
# Suppose we have categorical data and after encoding the numerical value become 0,1,2,3 and so on the ML model sometime
# think that its in sequence but actually it is not which effect the model performance.

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [26]:
# label encoding using pandas 
df["Country"] = df["Country"].astype("category") 
#first convert dtype into category, without converting into category we can't use cat.code 
df.dtypes

Country      category
Age           float64
Salary        float64
Purchased      object
dtype: object

In [27]:
df["Country"] = df["Country"].cat.codes 
#use cat.codes to convert the categorical data into numerical its kind of label encoding 
df

Country   Age   Salary Purchased
0        0  44.0  72000.0        No
1        2  27.0  48000.0       Yes
2        1  30.0  54000.0        No
3        2  38.0  61000.0        No
4        1  40.0      NaN       Yes
5        0  35.0  58000.0       Yes
6        2   NaN  52000.0        No
7        0  48.0  79000.0       Yes
8        1  50.0  83000.0        No
9        0  37.0  67000.0       Yes

In [43]:
# OneHotEncoding 
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse=False, handle_unknown= 'error', drop= 'first') #create one hot object
#drop = ‘first’ will handle dummy variable traps
OHE_df = pd.DataFrame(OHE.fit_transform(df[['Country']])) #df[['Country']] its required to convert into 2D array
OHE_df

0    1
0  0.0  0.0
1  0.0  1.0
2  1.0  0.0
3  0.0  1.0
4  1.0  0.0
5  0.0  0.0
6  0.0  1.0
7  0.0  0.0
8  1.0  0.0
9  0.0  0.0

In [44]:
# now merge the one hot encoder dummy variable to actual df but don't forgot to remove the actual column
df = df.join(OHE_df)
df

Country   Age   Salary Purchased    0    1
0   France  44.0  72000.0        No  0.0  0.0
1    Spain  27.0  48000.0       Yes  0.0  1.0
2  Germany  30.0  54000.0        No  1.0  0.0
3    Spain  38.0  61000.0        No  0.0  1.0
4  Germany  40.0      NaN       Yes  1.0  0.0
5   France  35.0  58000.0       Yes  0.0  0.0
6    Spain   NaN  52000.0        No  0.0  1.0
7   France  48.0  79000.0       Yes  0.0  0.0
8  Germany  50.0  83000.0        No  1.0  0.0
9   France  37.0  67000.0       Yes  0.0  0.0

In [69]:
df = df.drop(df.columns[[0]],axis=1,inplace= True)
print(df)

None


In [65]:
df.pop('Country')

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [72]:
# Using Pandas get dummies function
GDV = pd.get_dummies(df['Country'], prefix= 'Country', drop_first=True)
#In the case of 3 categories, we need only two indicator variables to preserve the information (and avoid collinearity). 
#That is why the pd.get_dummies function has another Boolean argument, drop_first=True, which drops the first category
GDV

Country_Germany  Country_Spain
0                0              0
1                0              1
2                1              0
3                0              1
4                1              0
5                0              0
6                0              1
7                0              0
8                1              0
9                0              0

In [73]:
df = pd.concat([df,GDV],axis = 1)
df # don't forgot to drop the first country column of categorical 

Country   Age   Salary Purchased  Country_Germany  Country_Spain
0   France  44.0  72000.0        No                0              0
1    Spain  27.0  48000.0       Yes                0              1
2  Germany  30.0  54000.0        No                1              0
3    Spain  38.0  61000.0        No                0              1
4  Germany  40.0      NaN       Yes                1              0
5   France  35.0  58000.0       Yes                0              0
6    Spain   NaN  52000.0        No                0              1
7   France  48.0  79000.0       Yes                0              0
8  Germany  50.0  83000.0        No                1              0
9   France  37.0  67000.0       Yes                0              0

In [ ]:
# Ordinal Encoding 
#An Ordinal Encoder is used to encode categorical features into an ordinal numerical value (ordered set). 
#This approach transforms categorical value to numerical value in ordered sets
#This encoding technique appears almost similar to Label Encoding. But, label encoding would not consider whether a variable is ordinal or not, but in the case of ordinal encoding,
#it will assign a sequence of numerical values as per the order of data.

In [ ]:
# Let’s create a sample ordinal categorical data related to the customer feedback survey, 
# and then we will apply the Ordinal Encoder technique. In this case, let’s say the feedback data is
# collected using a Likert scale in which numerical code 1 is assigned to Poor, 2 for Good, 3 for Very Good, 
# 4 for Excellent. If you observe, we know that 5 is better 4, 5 is much better than 3, but taking the difference 
# between 5 and 2 is meaningless (Excellent minus Good is meaningless).

In [74]:
# creating on pandas dataframes for ordinal data
data = {'Customer_Rating':['Poor','Good','Very Good','Excellent']}
df_ordinal = pd.DataFrame(data)
df_ordinal

Customer_Rating
0            Poor
1            Good
2       Very Good
3       Excellent

In [75]:
# creating dictionary for mapping the ordinal numerical value
Cust_rating_dict = {'Poor':1,'Good':2,'Very Good':3, 'Excellent':4}
#Assigning ordinal numerical value to all type of customer rating
df_ordinal['Customer_Rating'] = df_ordinal.Customer_Rating.map(Cust_rating_dict)
df_ordinal

Customer_Rating
0                1
1                2
2                3
3                4

# Splitting the datasets into training sets and Test sets


In [77]:
#from sklearn.cross_validation import train_test_split # train_test_split it is now in model_selection

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train,Y_test = train_test_split(x, y , test_size= 0.2, random_state=0)
#the random_state parameter is used for initializing the internal random number generator, which will decide
#the splitting of data into train and test indices in your case. If random_state is None or np. random, 
#then a randomly-initialized RandomState object is returned

In [85]:
# # How to configure training and testing split
# #There is no optimal split percentage.

# You must choose a split percentage that meets your project’s objectives with considerations that include:

# Computational cost in training the model.
# Computational cost in evaluating the model.
# Training set representativeness.
# Test set representativeness.
# Nevertheless, common split percentages include:

# Train: 80%, Test: 20%
# Train: 67%, Test: 33%
# Train: 50%, Test: 50%

# Feature Scaling

In [86]:
# # #Feature scaling is essential for machine learning algorithms that calculate distances between data.

# # #Why we need feature scaling

# # #---Machine learning algorithm just sees number — if there is a vast difference in the range say few ranging
# # #in thousands and few ranging in the tens, and it makes the underlying assumption that higher ranging numbers 
# # #have superiority of some sort. So these more significant number starts playing a more decisive role while
# # #training the model.

# # #Some examples of algorithms where feature scaling matters are:

# # K-nearest neighbors (KNN) with a Euclidean distance measure is sensitive to magnitudes
# # and hence should be scaled for all features to weigh in equally.

# # K-Means uses the Euclidean distance measure here feature scaling matters.

# # Scaling is critical while performing Principal Component Analysis(PCA).
# # PCA tries to get the features with maximum variance, and the variance is high for high magnitude
# # features and skews the PCA towards high magnitude features.

# # We can speed up gradient descent by scaling because θ descends quickly on small ranges and slowly on large ranges, 
# # and oscillates inefficiently down to the optimum when the variables are very uneven.

# #Type of feature scaling
# #-- MinMaxScaler or normalization 

# #Normalisation, also known as min-max scaling, is a scaling technique whereby the values in a column are shifted 
# #so that they are bounded between a fixed range of 0 and 1

# #--StandardScaler

# #standardisation or Z-score normalisation is another scaling technique whereby the values 
# #in a column are rescaled so that they demonstrate the properties of a standard Gaussian distribution,
# #that is mean = 0 and variance = 1.

# #--RobustScaler

# Scale features using statistics that are robust to outliers. This Scaler removes the median and scales the data according 
# to the quantile range (defaults to IQR: Interquartile Range).
# The IQR is the range between the 1st quartile (25th quantile) and the 3rd quartile (75th quantile).

# When to use Standarization and Normalization 

In [87]:
# Standardisation is generally preferred over normalisation in most machine learning context as it is especially 
# important when comparing the similarities between features based on certain distance measures. 
# This is most prominent in Principal Component Analysis (PCA), a dimensionality reduction algorithm, 
# where we are interested in the components that maximise the variance in the data.

#Before using Normalization scaling better to remove the outlier because this transformation doesn't change the distribuation 
# of the feature and due to the decreased standard deviation, the effects of outlier increase. therefore before normalization
#its recommended to handle the outlier.

In [20]:
#y = (x – min) / (max – min) formula 
from sklearn.preprocessing import MinMaxScaler
min_max_sc = MinMaxScaler()
X_train = min_max_sc.fit_transform(X_train)
X_test = min_max_sc.fit_transform(X_test)

In [21]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)